src/Isen.Dotnet.Web/Controllers/CityController.cs
using System;
using System.Linq;
using Isen.Dotnet.Library.Context;
using Isen.Dotnet.Library.Model;
using Isen.Dotnet.Library.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Isen.Dotnet.Web.Controllers
{
    public class CityController : BaseController<City>
    {
        public CityController(
            ILogger<CityController> logger,
            ApplicationDbContext context) : base(logger, context)
        {
        }
    }
}

src/Isen.Dotnet.Web/Controllers/PersonController.cs
using System;
using System.Linq;
using Isen.Dotnet.Library.Context;
using Isen.Dotnet.Library.Model;
using Isen.Dotnet.Library.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Isen.Dotnet.Web.Controllers
{
    public class PersonController : BaseController<Person>
    {
        public PersonController(
            ILogger<PersonController> logger,
            ApplicationDbContext context) : base(logger, context)
        {
        }               

        // Exemple d'override de la query : liste les personnes
        protected override IQueryable<Person> BaseQuery() =>
            base.BaseQuery()
                // Inclure BirthCity lors d'une requête faite sur une ville
                .Include(p => p.BirthCity)
                .Include(p => p.ResidenceCity)
                .Include(p => p.Service)
                .Include("RolePersons.Role")
                // Filtrer sur les villes qui commencent par Toul
                //.Where(p => p.BirthCity.StartsWith("Toul"))
                // Trier par ordre alpha des villes
                .OrderBy(p => p.BirthCity.Name);
    }
}

src/Isen.Dotnet.Web/Controllers/RoleController.cs
using System;
using System.Linq;
using Isen.Dotnet.Library.Context;
using Isen.Dotnet.Library.Model;
using Isen.Dotnet.Library.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Isen.Dotnet.Web.Controllers
{
    public class RoleController : BaseController<Role>
    {
        public RoleController(
            ILogger<RoleController> logger,
            ApplicationDbContext context) : base(logger, context)
        {
        }

        protected override IQueryable<Role> BaseQuery() =>
            base.BaseQuery()
                .Include("RolePersons.Person")
                .OrderBy(r => r.Name);
    }
}

src/Isen.Dotnet.Web/Controllers/ServiceController.cs
using System;
using System.Linq;
using Isen.Dotnet.Library.Context;
using Isen.Dotnet.Library.Model;
using Isen.Dotnet.Library.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Isen.Dotnet.Web.Controllers
{
    public class ServiceController : BaseController<Service>
    {
        public ServiceController(
            ILogger<ServiceController> logger,
            ApplicationDbContext context) : base(logger, context)
        {
        }
    }
}

src/Isen.Dotnet.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Isen.Dotnet.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <!-- Header : logo et menu -->
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Isen.Dotnet.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <!-- Menu stylé avec Bootstrap -->
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" 
                            asp-controller="Home" asp-action="Index">Accueil</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" 
                                id="navbarDropdown" role="button" 
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Personnes
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" 
                                    asp-controller="Person" asp-action="Index">Toutes</a>
                                <a class="dropdown-item" 
                                    asp-controller="Person" asp-action="Edit">Nouvelle...</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" 
                                id="navbarDropdown" role="button" 
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Villes
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" 
                                    asp-controller="City" asp-action="Index">Toutes</a>
                                <a class="dropdown-item" 
                                    asp-controller="City" asp-action="Edit">Nouvelle...</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" 
                                id="navbarDropdown" role="button" 
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Services
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" 
                                    asp-controller="Service" asp-action="Index">Toutes</a>
                                <a class="dropdown-item" 
                                    asp-controller="Service" asp-action="Edit">Nouveau...</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" 
                                id="navbarDropdown" role="button" 
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Roles
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" 
                                    asp-controller="Role" asp-action="Index">Toutes</a>
                                <a class="dropdown-item" 
                                    asp-controller="Role" asp-action="Edit">Nouveau...</a>
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" 
                            asp-controller="Playground" asp-action="Index">Terrain de jeu</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" 
                            asp-controller="Home" asp-action="Ajax">Ajax</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" 
                            asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <!-- Zone de contenu -->
    <div class="container">
        <main role="main" class="pb-3">
            <!-- Razor : insère la vue ici (ex : Index.cshtml) -->
            @RenderBody()
        </main>
    </div>

    <!-- Footer : copyright, mentions légales et autres conneries -->
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Isen.Dotnet.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    <!-- Insertion des librairies et scripts JS au dernier moment -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- ??? -->
    @RenderSection("Scripts", required: false)
</body>
</html>